### ISSUE TITLE
Invalid file type...skipping download

### ISSUE THREAD

**Issue by abasgames** [CubeMath/UCHFastDL2#6]
Invalid file type...skipping download of scripts/maps/hl_weapons/weapon_hl357.as
Invalid file type...skipping download of scripts/maps/cubemath/trigger_once_mp.as
Invalid file type...skipping download of scripts/maps/cubemath/trigger_mediaplayer.as

**Comment by incognico** [comment]
Nothing to worry about, it is normal (and nothing can be done about it).
